# Generated by Django 3.2.16 on 2023-01-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_calorie',
            field=models.IntegerField(default=0),
        ),
    ]
